### ISSUE TITLE
Investigate the use of another Docker base image

### ISSUE THREAD

**Issue by VaiTon** [Difegue/action-perlcritic#5]
For example: [pipelinecomponents/perl-critic](https://hub.docker.com/r/pipelinecomponents/perl-critic)

Which seems to be mantained and based on alpine (16 MB instead of 231.65 MB)

**Comment by Difegue** [comment]
Thanks for notifying me about this! I didn't know there were prebuilt critic Docker images other than the aging avast one.  

I've created an `alpine-test` branch that switches to this image as a base, and if all goes well during testing (looking good so far) I'll be releasing a v2.5 on Marketplace soon enough. ✌️

**Comment by VaiTon** [comment]
Thank you very much @Difegue 🎉
